create type rating_star as enum ('1', '2', '3', '4', '5');

create table bookmarks (
	id integer primary key generated by default as identity,
	title text not null,
	url text not null,
	description text,
	rating rating_star not null
);